# -*- coding: utf-8 -*-
"""Panda.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouPobgC2zJvckwy-VVmCiNIBYhlMUp61
"""

import pandas as pd
data = pd.read_csv('/content/medals_by_country_2016.csv')
data.head(10)

data.Bronze

data.loc[3]

data[1:6]